// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXJVECSVi5xWDMtkwK_GrzRC2R8bQ4iSc',
    appId: '1:386965574222:web:54baaa1c1704fa70a4291f',
    messagingSenderId: '386965574222',
    projectId: 'singmet-2e7f8',
    authDomain: 'singmet-2e7f8.firebaseapp.com',
    storageBucket: 'singmet-2e7f8.firebasestorage.app',
    measurementId: 'G-9CDEVM23LP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ-BuPX_Ab5uwbEQ_dJTXVlw8WUkkj7wA',
    appId: '1:386965574222:android:44021141976293a5a4291f',
    messagingSenderId: '386965574222',
    projectId: 'singmet-2e7f8',
    storageBucket: 'singmet-2e7f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF7cED-sl7J7iJzbPmFyxwg6_Jm8OJA4o',
    appId: '1:386965574222:ios:d6edd86c6b90563fa4291f',
    messagingSenderId: '386965574222',
    projectId: 'singmet-2e7f8',
    storageBucket: 'singmet-2e7f8.firebasestorage.app',
    iosBundleId: 'com.example.sightMateApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF7cED-sl7J7iJzbPmFyxwg6_Jm8OJA4o',
    appId: '1:386965574222:ios:d6edd86c6b90563fa4291f',
    messagingSenderId: '386965574222',
    projectId: 'singmet-2e7f8',
    storageBucket: 'singmet-2e7f8.firebasestorage.app',
    iosBundleId: 'com.example.sightMateApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXJVECSVi5xWDMtkwK_GrzRC2R8bQ4iSc',
    appId: '1:386965574222:web:c663b9729805308fa4291f',
    messagingSenderId: '386965574222',
    projectId: 'singmet-2e7f8',
    authDomain: 'singmet-2e7f8.firebaseapp.com',
    storageBucket: 'singmet-2e7f8.firebasestorage.app',
    measurementId: 'G-7DT8ZDDKDD',
  );
}
